In [1]:
# NOTE: Script to run LSTM over selection of df's

# Libaries
import pandas as pd
import numpy as np
import pickle

from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense, Dropout
from sklearn.model_selection import TimeSeriesSplit

import sys
sys.path.append('/Users/ludwigbaunach/Documents/Studium/PhD/Alaiko/Paper_1_Project/Main/src')
from utils.data_split import ml_data_date_split

import warnings
warnings.filterwarnings('ignore')

2023-06-29 09:22:15.059814: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [31]:
# Custom Functions

# Split a univariate sequence into samples
def split_sequences(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # Find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # Check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # Gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)


# LSTM Forecast
def LSTM_forecast(train_data, n_steps_in, n_steps_out, epochs, batch_size):
    
    # Set up data
    # Get quantity column as np array
    sequence = train_data['quantity'].values
    # Split into input/output
    X, y = split_sequences(sequence, n_steps_in, n_steps_out)

    # Reshape X to fit the LSTM input shape (samples, timesteps, features)
    X = X.reshape((X.shape[0], X.shape[1], 1))
    
    # Define Model 
    
    # Model
    model = Sequential()
    model.add(LSTM(200, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
    model.add(LSTM(100, activation='relu'))
    model.add(Dense(n_steps_out))
    model.compile(optimizer='adam', loss='mse')

    # Train
    
    # Fit model
    model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=0)

    # Forecast
    
    # Get last n_steps_in quantities
    x_input = sequence[-n_steps_in:]
    x_input = x_input.reshape((1, n_steps_in, 1))

    # Predict
    yhat = model.predict(x_input, verbose=0)
    # Flatten yhat
    yhat_1d = yhat.flatten()

    return yhat_1d


def LSTM_backtesting(df, tscv):
    # Initialize an empty lists to store predictions, actuals and dates
    preds = []
    actuals = []
    dates = []

    # loop over pre-defined time series split / time series cross validation (tscv)
    for i, (train_index, test_index) in enumerate(tscv.split(df)):
        # Train and test data
        train_fold, test_fold = df.iloc[train_index], df.iloc[test_index]

        # Append Dates
        dates_fold = df.date.iloc[test_index].tolist()

        # Track
        print(f"Fold Nr. = {i}")

        # Predict on the current test fold
        y_pred_fold = LSTM_forecast(train_fold, n_steps_in, n_steps_out, epochs, batch_size)

        # append scores and predictions
        preds.append(y_pred_fold.tolist())
        actuals.append(test_fold.quantity.tolist())
        dates.append(dates_fold)

    # make df that holds predictions and actuals
    # flatten nested lists
    dates = np.concatenate(dates).tolist()
    actuals = np.concatenate(actuals).tolist()
    preds = np.concatenate(preds).tolist()

    # Error analysis
    error = pd.DataFrame({
        "date": dates,
        "actual": actuals,
        "pred": preds
    }).reset_index(drop=True)

    return error

In [34]:
%%time
# Set Modelling Parameters

# Set seed
np.random.seed(42)

# Horizon
time_horizon = 9
n_steps_in = 30
n_steps_out = time_horizon
n_features = 1

# TimeSeriesSplit
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=time_horizon)

# Model parameters
batch_size = 32
epochs = 150

# define DFs and groups

df_list = ["L_3"]
#df_list = ["L_3", "L_4", "L_6"]
group_list = ["warehouse_chain"]
#group_list = ["warehouse_chain", "new_customer_id", "empty"]

# Load data
test_data = {}
for i in df_list:
    test_data[i] = pd.read_pickle(f"../data/processed/{i}_test.pkl")

# Initialize an empty dictionary to store the results
results = {}

# lightGBM modelling
for level, group in zip(df_list, group_list):

    # Initialize DataFrames to store the backtest and forecasted values
    backtest_values = pd.DataFrame(columns=["date", "actual", "pred", "level", "group"])
    forecast_values = pd.DataFrame(columns=["date", "actual", "pred", "level", "group"])

    # Select the right level
    df = test_data[level].copy()

    # Select the right group

    if level == "L_6":

        print("Group:", "L_6")

        # selected group
        group_df = df.copy()

        # Define Data
        train_df, test_df = ml_data_date_split(group_df, 8)  # split data with custom function

        print("Start backtest:")
        # Backtest
        temp_backtest_df = LSTM_backtesting(train_df, tscv)
        temp_backtest_df["level"] = level
        temp_backtest_df["group"] = "empty"

        backtest_values = pd.concat([backtest_values, temp_backtest_df])

        print("Start forecast:")
        y_pred = LSTM_forecast(train_df, n_steps_in, n_steps_out, epochs, batch_size)

        temp_forecast_df = pd.DataFrame({'date': test_df.date,
                                         'actual': test_df.quantity,
                                         'pred': y_pred})
        temp_forecast_df["level"] = level
        temp_forecast_df["group"] = "empty"

        forecast_values = pd.concat([forecast_values, temp_forecast_df])

    else:

        for i_ts in df[group].unique():
            print("Group:", i_ts)

            # selected group
            group_df = df[df[group] == i_ts]

            # Define Data
            train_df, test_df = ml_data_date_split(group_df, 8)  # split data with custom function

            print("Start backtest:")
            # Backtest
            temp_backtest_df = LSTM_backtesting(train_df, tscv)
            temp_backtest_df["level"] = level
            temp_backtest_df["group"] = i_ts

            backtest_values = pd.concat([backtest_values, temp_backtest_df])

            print("Start forecast:")
            y_pred = LSTM_forecast(train_df, model, n_steps_in, n_steps_out, epochs, batch_size)

            temp_forecast_df = pd.DataFrame({'date': test_df.date,
                                             'actual': test_df.quantity,
                                             'pred': y_pred})
            temp_forecast_df["level"] = level
            temp_forecast_df["group"] = i_ts

            forecast_values = pd.concat([forecast_values, temp_forecast_df])

    # Store the backtest and prediction data frames in the results dictionary
    # with the corresponding name including the category_name
    results[f"{level}"] = {
        'backtest': backtest_values,
        'pred': forecast_values
    }

Group: WH-Chain-1
Start backtest:
Fold Nr. = 0
Fold Nr. = 1
Fold Nr. = 2
WARNING:tensorflow:5 out of the last 36 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fb521c108b0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Fold Nr. = 3
WARNING:tensorflow:6 out of the last 37 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fb521c3c0d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Fold Nr. = 4
Start forecast:

TypeError: LSTM_forecast() takes 5 positional arguments but 6 were given

In [35]:
results["L_3"]

KeyError: 'L_3'

In [30]:
%%time





error3 =  LSTM_backtesting(train, model, tscv)
error3

Fold Nr. = 0
Fold Nr. = 1
Fold Nr. = 2
Fold Nr. = 3
Fold Nr. = 4
CPU times: user 30min, sys: 6min 11s, total: 36min 12s
Wall time: 8min 25s

         date   actual         pred
0  2022-10-13   3142.0  2043.555908
1  2022-10-14   2648.0  2021.061035
2  2022-10-15   1954.0  2061.219482
3  2022-10-16   2442.0  1988.887695
4  2022-10-17   2012.0  2045.393433
5  2022-10-18   3468.0  2060.311768
6  2022-10-19   2732.0  2084.658447
7  2022-10-20   2922.0  2161.358887
8  2022-10-21   2467.0  2042.018311
9  2022-10-22   2098.0  1806.274170
10 2022-10-23   4427.0  1799.604126
11 2022-10-24   3563.0  1924.049561
12 2022-10-25   3266.0  1784.688354
13 2022-10-26   2807.0  1988.211060
14 2022-10-27   3538.0  1855.107910
15 2022-10-28  11868.0  1800.396973
16 2022-10-29   6568.0  1862.019897
17 2022-10-30   3288.0  1878.729980
18 2022-10-31   3041.0  1044.825073
19 2022-11-01   3483.0  1176.311035
20 2022-11-02   3272.0  1213.651978
21 2022-11-03   3057.0  1129.126465
22 2022-11-04   2984.0  1182.661987
23 2022-11-05  10685.0  1206.905640
24 2022-11-06  15224.0  1195.756714
25 2022-11-07   5646.0  1208.855469
26 2022-11-08   4997.0  1231.786499
27 2022-11-09   4821.0  3105.669922
28 2022-11-10   5078.0  3079.315430
29 2022-11-11   9049.0  3251.006836
30 2022-11-12   4598.0  3157.897461
31 2022-11-13   4015.0  3219.170410
32 2022-11-14   3170.0  3215.175049
33 2022-11-15   3345.0  3294.300293
34 2022-11-16   3417.0  3230.641602
35 2022-11-17  10189.0  3250.723877
36 2022-11-18  18548.0  3912.537354
37 2022-11-19   9135.0  3900.294922
38 2022-11-20  14733.0  3942.835693
39 2022-11-21  10952.0  3903.299072
40 2022-11-22  11340.0  3975.025635
41 2022-11-23   9387.0  3901.864258
42 2022-11-24  10888.0  3913.232422
43 2022-11-25  21906.0  3933.971191
44 2022-11-26  10314.0  3922.789795

In [29]:
%%time
error2 =  LSTM_backtesting(train, model, tscv)
error2

Fold Nr. = 0
Fold Nr. = 1
Fold Nr. = 2
Fold Nr. = 3
Fold Nr. = 4
CPU times: user 29min 49s, sys: 6min 7s, total: 35min 56s
Wall time: 7min 45s

         date   actual  pred
0  2022-10-13   3142.0   NaN
1  2022-10-14   2648.0   NaN
2  2022-10-15   1954.0   NaN
3  2022-10-16   2442.0   NaN
4  2022-10-17   2012.0   NaN
5  2022-10-18   3468.0   NaN
6  2022-10-19   2732.0   NaN
7  2022-10-20   2922.0   NaN
8  2022-10-21   2467.0   NaN
9  2022-10-22   2098.0   NaN
10 2022-10-23   4427.0   NaN
11 2022-10-24   3563.0   NaN
12 2022-10-25   3266.0   NaN
13 2022-10-26   2807.0   NaN
14 2022-10-27   3538.0   NaN
15 2022-10-28  11868.0   NaN
16 2022-10-29   6568.0   NaN
17 2022-10-30   3288.0   NaN
18 2022-10-31   3041.0   NaN
19 2022-11-01   3483.0   NaN
20 2022-11-02   3272.0   NaN
21 2022-11-03   3057.0   NaN
22 2022-11-04   2984.0   NaN
23 2022-11-05  10685.0   NaN
24 2022-11-06  15224.0   NaN
25 2022-11-07   5646.0   NaN
26 2022-11-08   4997.0   NaN
27 2022-11-09   4821.0   NaN
28 2022-11-10   5078.0   NaN
29 2022-11-11   9049.0   NaN
30 2022-11-12   4598.0   NaN
31 2022-11-13   4015.0   NaN
32 2022-11-14   3170.0   NaN
33 2022-11-15   3345.0   NaN
34 2022-11-16   3417.0   NaN
35 2022-11-17  10189.0   NaN
36 2022-11-18  18548.0   NaN
37 2022-11-19   9135.0   NaN
38 2022-11-20  14733.0   NaN
39 2022-11-21  10952.0   NaN
40 2022-11-22  11340.0   NaN
41 2022-11-23   9387.0   NaN
42 2022-11-24  10888.0   NaN
43 2022-11-25  21906.0   NaN
44 2022-11-26  10314.0   NaN

In [26]:
test_12 = LSTM_backtesting(train_df, model, tscv)
test_12

Fold Nr. = 0
Fold Nr. = 1
Fold Nr. = 2
Fold Nr. = 3
Fold Nr. = 4

         date   actual  pred
0  2022-10-13   3142.0   NaN
1  2022-10-14   2648.0   NaN
2  2022-10-15   1954.0   NaN
3  2022-10-16   2442.0   NaN
4  2022-10-17   2012.0   NaN
5  2022-10-18   3468.0   NaN
6  2022-10-19   2732.0   NaN
7  2022-10-20   2922.0   NaN
8  2022-10-21   2467.0   NaN
9  2022-10-22   2098.0   NaN
10 2022-10-23   4427.0   NaN
11 2022-10-24   3563.0   NaN
12 2022-10-25   3266.0   NaN
13 2022-10-26   2807.0   NaN
14 2022-10-27   3538.0   NaN
15 2022-10-28  11868.0   NaN
16 2022-10-29   6568.0   NaN
17 2022-10-30   3288.0   NaN
18 2022-10-31   3041.0   NaN
19 2022-11-01   3483.0   NaN
20 2022-11-02   3272.0   NaN
21 2022-11-03   3057.0   NaN
22 2022-11-04   2984.0   NaN
23 2022-11-05  10685.0   NaN
24 2022-11-06  15224.0   NaN
25 2022-11-07   5646.0   NaN
26 2022-11-08   4997.0   NaN
27 2022-11-09   4821.0   NaN
28 2022-11-10   5078.0   NaN
29 2022-11-11   9049.0   NaN
30 2022-11-12   4598.0   NaN
31 2022-11-13   4015.0   NaN
32 2022-11-14   3170.0   NaN
33 2022-11-15   3345.0   NaN
34 2022-11-16   3417.0   NaN
35 2022-11-17  10189.0   NaN
36 2022-11-18  18548.0   NaN
37 2022-11-19   9135.0   NaN
38 2022-11-20  14733.0   NaN
39 2022-11-21  10952.0   NaN
40 2022-11-22  11340.0   NaN
41 2022-11-23   9387.0   NaN
42 2022-11-24  10888.0   NaN
43 2022-11-25  21906.0   NaN
44 2022-11-26  10314.0   NaN

In [14]:
# LSTM Forecast
def LSTM_forecast(train_data, model, n_steps_in, n_steps_out, epochs, batch_size):
    # Set up data
    # Get quantity column as np array
    sequence = train_data['quantity'].values

    # Split into input/output
    X, y = split_sequences(sequence, n_steps_in, n_steps_out)

    # Reshape X to fit the LSTM input shape (samples, timesteps, features)
    X = X.reshape((X.shape[0], X.shape[1], 1))

    # Train
    # Fit model
    model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=0)

    # Forecast
    # Get last n_steps_in quantities
    x_input = sequence[-n_steps_in:]
    x_input = x_input.reshape((1, n_steps_in, 1))

    # Predict
    yhat = model.predict(x_input, verbose=0)
    # Flatten yhat
    yhat_1d = yhat.flatten()

    return yhat_1d

df_test = test_data["L_3"]
df_test = df_test[df_test["warehouse_chain"] == "WH-Chain-3"]

In [15]:
%%time
train,test = ml_data_date_split(df_test, 8)
yhat2 = LSTM_forecast(train, model, n_steps_in, n_steps_out, epochs, batch_size)

CPU times: user 5min 39s, sys: 1min 7s, total: 6min 46s
Wall time: 1min 28s

In [17]:
yhat2

array([6096.3574, 6169.8594, 6185.2563, 6346.7397, 6415.6606, 6488.465 ,
       6739.0264, 6854.357 , 6686.984 ], dtype=float32)

In [28]:
train_df

,date,warehouse_chain,quantity,tm_w_end,tm_dy_sin,tm_dy_cos,tm_dm_sin,tm_dm_cos,tm_wy_sin,tm_wy_cos,...,holiday_Pfingstmontag,holiday_Reformationstag,holiday_Tag_der_Deutschen_Einheit,holiday_Zweiter_Weihnachtstag,blackweek,blackweekend,aftercyberweek,tm_y_0,tm_y_1,tm_y_2
379,2021-03-30,WH-Chain-3,1.0,0,-0.952574,-0.304308,-2.012985e-01,0.979530,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
382,2021-03-31,WH-Chain-3,0.0,0,-0.966457,-0.256827,-2.449294e-16,1.000000,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
385,2021-04-01,WH-Chain-3,10.0,0,-0.977976,-0.208718,2.012985e-01,0.979530,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
388,2021-04-02,WH-Chain-3,0.0,0,-0.987101,-0.160098,3.943559e-01,0.918958,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
391,2021-04-03,WH-Chain-3,0.0,1,-0.993811,-0.111087,5.712682e-01,0.820763,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2022-11-22,WH-Chain-3,11340.0,0,-0.316066,-0.948737,-9.680771e-01,-0.250653,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2188,2022-11-23,WH-Chain-3,9387.0,0,-0.362598,-0.931946,-9.987165e-01,-0.050649,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2191,2022-11-24,WH-Chain-3,10888.0,0,-0.408243,-0.912873,-9.884683e-01,0.151428,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2194,2022-11-25,WH-Chain-3,21906.0,0,-0.452888,-0.891567,-9.377521e-01,0.347305,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2197,2022-11-26,WH-Chain-3,10314.0,1,-0.496425,-0.868079,-8.486443e-01,0.528964,-0.652822,0.757511,...,0,0,0,0,0,1,0,0,0,1

In [27]:
train

,date,warehouse_chain,quantity,tm_w_end,tm_dy_sin,tm_dy_cos,tm_dm_sin,tm_dm_cos,tm_wy_sin,tm_wy_cos,...,holiday_Pfingstmontag,holiday_Reformationstag,holiday_Tag_der_Deutschen_Einheit,holiday_Zweiter_Weihnachtstag,blackweek,blackweekend,aftercyberweek,tm_y_0,tm_y_1,tm_y_2
379,2021-03-30,WH-Chain-3,1.0,0,-0.952574,-0.304308,-2.012985e-01,0.979530,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
382,2021-03-31,WH-Chain-3,0.0,0,-0.966457,-0.256827,-2.449294e-16,1.000000,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
385,2021-04-01,WH-Chain-3,10.0,0,-0.977976,-0.208718,2.012985e-01,0.979530,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
388,2021-04-02,WH-Chain-3,0.0,0,-0.987101,-0.160098,3.943559e-01,0.918958,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
391,2021-04-03,WH-Chain-3,0.0,1,-0.993811,-0.111087,5.712682e-01,0.820763,0.999561,0.029633,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2022-11-22,WH-Chain-3,11340.0,0,-0.316066,-0.948737,-9.680771e-01,-0.250653,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2188,2022-11-23,WH-Chain-3,9387.0,0,-0.362598,-0.931946,-9.987165e-01,-0.050649,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2191,2022-11-24,WH-Chain-3,10888.0,0,-0.408243,-0.912873,-9.884683e-01,0.151428,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2194,2022-11-25,WH-Chain-3,21906.0,0,-0.452888,-0.891567,-9.377521e-01,0.347305,-0.652822,0.757511,...,0,0,0,0,1,0,0,0,0,1
2197,2022-11-26,WH-Chain-3,10314.0,1,-0.496425,-0.868079,-8.486443e-01,0.528964,-0.652822,0.757511,...,0,0,0,0,0,1,0,0,0,1

In [19]:
%%time
error =  LSTM_backtesting(train, model, tscv)
error

Fold Nr. = 0
Fold Nr. = 1
Fold Nr. = 2
Fold Nr. = 3
Fold Nr. = 4
CPU times: user 28min 18s, sys: 5min 49s, total: 34min 7s
Wall time: 7min 27s

         date   actual         pred
0  2022-10-13   3142.0  2157.958984
1  2022-10-14   2648.0  2190.646973
2  2022-10-15   1954.0  2155.380127
3  2022-10-16   2442.0  2183.671875
4  2022-10-17   2012.0  2187.176758
5  2022-10-18   3468.0  2193.703369
6  2022-10-19   2732.0  2285.228027
7  2022-10-20   2922.0  2245.639648
8  2022-10-21   2467.0  2275.179688
9  2022-10-22   2098.0  1872.910889
10 2022-10-23   4427.0  1822.755493
11 2022-10-24   3563.0  1873.464478
12 2022-10-25   3266.0  1773.171875
13 2022-10-26   2807.0  1829.001221
14 2022-10-27   3538.0  1953.499878
15 2022-10-28  11868.0  1932.393677
16 2022-10-29   6568.0  1954.076172
17 2022-10-30   3288.0  1910.146484
18 2022-10-31   3041.0  1597.558960
19 2022-11-01   3483.0  1619.940430
20 2022-11-02   3272.0  1655.853149
21 2022-11-03   3057.0  1587.186646
22 2022-11-04   2984.0  1588.545288
23 2022-11-05  10685.0  1606.437622
24 2022-11-06  15224.0  1689.189697
25 2022-11-07   5646.0  1705.512207
26 2022-11-08   4997.0  1712.102051
27 2022-11-09   4821.0  2899.732422
28 2022-11-10   5078.0  2948.898438
29 2022-11-11   9049.0  3008.081787
30 2022-11-12   4598.0  3009.926514
31 2022-11-13   4015.0  2979.708252
32 2022-11-14   3170.0  3070.230713
33 2022-11-15   3345.0  3118.611572
34 2022-11-16   3417.0  3167.000977
35 2022-11-17  10189.0  3210.598145
36 2022-11-18  18548.0  1492.701050
37 2022-11-19   9135.0  1659.256592
38 2022-11-20  14733.0  1355.161499
39 2022-11-21  10952.0  1639.755615
40 2022-11-22  11340.0  1433.245483
41 2022-11-23   9387.0  1753.755249
42 2022-11-24  10888.0  1561.585938
43 2022-11-25  21906.0  1893.153076
44 2022-11-26  10314.0  1919.158447