In [1]:
# Libaries
import warnings
warnings.filterwarnings('ignore')

import sys
import pandas as pd
import numpy as np
import math 

from itertools import product

In [64]:
sys.path

['/Users/ludwigbaunach/Documents/Studium/PhD/Alaiko/Paper_1_Project/Main/notebooks',
 '/opt/miniconda3/envs/snowflakes/lib/python310.zip',
 '/opt/miniconda3/envs/snowflakes/lib/python3.10',
 '/opt/miniconda3/envs/snowflakes/lib/python3.10/lib-dynload',
 '',
 '/opt/miniconda3/envs/snowflakes/lib/python3.10/site-packages',
 '/Users/ludwigbaunach/Documents/Studium/PhD/Alaiko/Paper_1_Project/Main/src']

#### Load Datasets

In [35]:
### ORDER DATA ###
df = pd.read_csv("../data/processed/b2c_orders_clean.csv")

### WEATHER DATA ###
weather_df = pd.read_csv("../data/intermediate/weather.csv")

### Price DATA ###
prices_df = pd.read_csv("../data/intermediate/prices.csv")

### Holiday Data

# To-Do

1. Create Product Grid

From here every other grid will be created.

2. Create Price Features, Quantity/Momentum features on product level.


3. Brainstorm how to create other aggregation level.

List of Datasets I need

Product
Product - Warehouse
Product - Shop
Product - State
Shop
State
Warehouse
Cluster - Product
Cluster - Shop

## 1. Create Product Grid

In [5]:
# Creaet date column 
df["date"] = pd.to_datetime(df["order_datetime"]).dt.date
df["date"] = pd.to_datetime(df.date)

### 1. Create Basic Dataset with quantity per product for all dates

In [13]:
df.columns

Index(['date', 'order_id', 'order_item_id', 'customer_id', 'order_datetime',
       'quantity', 'product_variant_id', 'warehouse_chain', 'item_discount',
       'billing_country', 'billing_zip', 'business_type', 'filled_prices'],
      dtype='object')

In [14]:
q_df = df.groupby(["product_variant_id", "date"]).mean().drop(
    columns=["order_id", "order_item_id", "customer_id"]) # Drop useless columns 

q_df["quantity"] = df.groupby(["product_variant_id", "date"]).quantity.sum()

In [15]:
### SALES PRODUCT LEVEL GRID BASED FOR ALL DATES 
def create_sales_grid(df, group_by):

    # Set start and end date based on original df
    start_date = df.index.get_level_values(1).min() 
    end_date = df.index.get_level_values(1).max()

    # create list of all product ids
    product_ids = df.index.get_level_values(0).unique()

    # Create a date range base on start and end date 
    date_range = pd.date_range(start_date, end_date)

    # create cartesian product of dates and product_variant id to get full range of dates per product
    C_product = pd.DataFrame.from_records(product(product_ids,date_range), columns = group_by)
    C_product = C_product.set_index(group_by)

    # Merge with q_df, fill NaN with 0 to get real sales data
    # Before 0 sales were simply not present in the dataset
    result_df = C_product.join(q_df, on=group_by, how="left").fillna(0)
    
    # Delete 0 sales up until point of first sale 
    
    return result_df


group_by = ['product_variant_id', 'date']

# Unfiltered Sales data
product_sales = create_sales_grid(q_df, group_by)

In [16]:
# Now delete all 0 quantity data before first entry and after last entry

# create turple to Indicate first and last index of non zero entries in "quantity"
# thus, now we deleted sales data before first index
q_valid_index = product_sales.reset_index().groupby('product_variant_id')\
                                            .apply(lambda x: (x[x['quantity']>0].index[0],x[x['quantity']>0].index[-1]))

# Use boolean indexing
# 1. Create mask, same length as df that is true for all indices set in the step before 
mask = np.zeros(len(product_sales), dtype=bool)
for start, end in q_valid_index:
    mask[start:end+1] = True

product_sales = product_sales.reset_index().loc[mask]

In [17]:
product_sales.set_index(["product_variant_id", "date"], inplace=True)

In [46]:
product_sales.drop(columns=["item_discount", "filled_prices"], inplace=True)

### 2. Add Time Features

In [19]:
##### TIME FEATURES #####
def to_time_feature(df):
    
    product_sales.reset_index(inplace=True)
    
    df["date"] = pd.to_datetime(df.date)
    # Make some features from date
    df['tm_d'] = df.date.dt.day.astype(np.int8) # Day of month
    df['tm_w'] = df.date.dt.week.astype(np.int8) # week of year
    df['tm_m'] = df.date.dt.month.astype(np.int8) # month of year
    df['tm_y'] = df.date.dt.year # year
    df['tm_y'] = (df['tm_y'] - df['tm_y'].min()).astype(np.int8) # year - min year = number of year
    df['tm_wm'] = df['tm_d'].apply(lambda x: math.ceil(x / 7)).astype(np.int8) # number of week in month

    df['tm_dw'] = df.date.dt.dayofweek.astype(np.int8)  # number of day in week
    df['tm_w_end'] = (df['tm_dw'] >= 5).astype(np.int8)  # indicate Weekend

    return df

product_sales = to_time_feature(product_sales)
#test
#product_sales

### 3. Add momentum and lag features

In [58]:
# Momentum Features: Rolling averages and standard dev 7 & 14 days  
product_sales['q_roll_mean_7d'] = product_sales.groupby(['product_variant_id'])['quantity'].rolling(7).mean().reset_index().quantity
product_sales['q_roll_std_7d'] = product_sales.groupby(['product_variant_id'])['quantity'].rolling(7).std().reset_index().quantity
product_sales['q_roll_mean_14d'] = product_sales.groupby(['product_variant_id'])['quantity'].rolling(14).mean().reset_index().quantity
product_sales['q_roll_std_14d'] = product_sales.groupby(['product_variant_id'])['quantity'].rolling(14).std().reset_index().quantity

# Lag Features 1 day, 7 day, 14 day & 28 day
product_sales['q_lag_1d'] = product_sales.groupby(['product_variant_id'])['quantity'].shift(periods=1)
product_sales['q_lag_7d'] = product_sales.groupby(['product_variant_id'])['quantity'].shift(periods=7)
product_sales['q_lag_14d'] = product_sales.groupby(['product_variant_id'])['quantity'].shift(periods=14)
product_sales['q_lag_28d'] = product_sales.groupby(['product_variant_id'])['quantity'].shift(periods=28)
product_sales["q_mean_lag_7_14_28"] = (product_sales['q_lag_7d'] + product_sales['q_lag_14d'] + product_sales['q_lag_28d'])/3

# test
#product_sales

,product_variant_id,date,quantity,tm_d,tm_w,tm_m,tm_y,tm_wm,tm_dw,tm_w_end,q_roll_mean_7d,q_roll_std_7d,q_roll_mean_14d,q_roll_std_14d,q_lag_1d,q_lag_7d,q_lag_14d,q_lag_28d,q_mean_lag_7_14_28
0,-9.223350e+18,2020-09-17,5.0,17,38,9,0,3,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-9.223350e+18,2020-09-18,0.0,18,38,9,0,3,4,0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
2,-9.223350e+18,2020-09-19,0.0,19,38,9,0,3,5,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,-9.223350e+18,2020-09-20,0.0,20,38,9,0,3,6,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,-9.223350e+18,2020-09-21,0.0,21,39,9,0,3,0,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
5,-9.223350e+18,2020-09-22,0.0,22,39,9,0,4,1,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
6,-9.223350e+18,2020-09-23,0.0,23,39,9,0,4,2,0,0.714286,1.889822,NaN,NaN,0.0,NaN,NaN,NaN,NaN
7,-9.223350e+18,2020-09-24,4.0,24,39,9,0,4,3,0,0.571429,1.511858,NaN,NaN,0.0,5.0,NaN,NaN,NaN
8,-9.223350e+18,2020-09-25,0.0,25,39,9,0,4,4,0,0.571429,1.511858,NaN,NaN,4.0,0.0,NaN,NaN,NaN
9,-9.223350e+18,2020-09-26,0.0,26,39,9,0,4,5,1,0.571429,1.511858,NaN,NaN,0.0,0.0,NaN,NaN,NaN
10,-9.223350e+18,2020-09-27,0.0,27,39,9,0,4,6,1,0.571429,1.511858,NaN,NaN,0.0,0.0,NaN,NaN,NaN
11,-9.223350e+18,2020-09-28,0.0,28,40,9,0,4,0,0,0.571429,1.511858,NaN,NaN,0.0,0.0,NaN,NaN,NaN
12,-9.223350e+18,2020-09-29,0.0,29,40,9,0,5,1,0,0.571429,1.511858,NaN,NaN,0.0,0.0,NaN,NaN,NaN
13,-9.223350e+18,2020-09-30,0.0,30,40,9,0,5,2,0,0.571429,1.511858,0.642857,1.645841,0.0,0.0,NaN,NaN,NaN
14,-9.223350e+18,2020-10-01,1.0,1,40,10,0,1,3,0,0.142857,0.377964,0.357143,1.081818,0.0,4.0,5.0,NaN,NaN
15,-9.223350e+18,2020-10-02,0.0,2,40,10,0,1,4,0,0.142857,0.377964,0.357143,1.081818,1.0,0.0,0.0,NaN,NaN
16,-9.223350e+18,2020-10-03,0.0,3,40,10,0,1,5,1,0.142857,0.377964,0.357143,1.081818,0.0,0.0,0.0,NaN,NaN
17,-9.223350e+18,2020-10-04,0.0,4,40,10,0,1,6,1,0.142857,0.377964,0.357143,1.081818,0.0,0.0,0.0,NaN,NaN
18,-9.223350e+18,2020-10-05,0.0,5,41,10,0,1,0,0,0.142857,0.377964,0.357143,1.081818,0.0,0.0,0.0,NaN,NaN
19,-9.223350e+18,2020-10-06,0.0,6,41,10,0,1,1,0,0.142857,0.377964,0.357143,1.081818,0.0,0.0,0.0,NaN,NaN

### CREATE ONE BIG DATASET 

I have three datasets: 

- product_sales_df
- weather_df
- prices_df

Join and allign them all:

#### To-Do
1. Join prices_df and product_sales on date and product_variant_id
2. Join weahter_df[weather_df["state"] = "deutschland"] only on date!

## Problem prices of products in weeks where there were no sales

In [60]:
final_df = pd.merge(product_sales, prices_df, how='left', 
                    left_on=['product_variant_id'], right_on=['product_variant_id'])

In [61]:
# Save 
final_df.to_csv("../data/final/product_level.csv")